### ISSUE TITLE
Cartoon Guide to Lob's theorem missing images

### ISSUE THREAD

**Issue by Raemon** [LessWrong2/Lesswrong2#1012]
https://www.lesswrong.com/posts/ALCnqX6Xx8bpFMZq3/the-cartoon-guide-to-loeb-s-theorem

Images are currently still available here:

https://www.scribd.com/doc/4844564/Cartoon-Guide-to-Lob-s-Theorem

**Comment by jimrandomh** [comment]
Technically speaking, it's a missing Scribd embed, not missing images, and it's failing to load because it's a Flash applet trying to load over http on an https site, not because the link doesn't go to a potentially-valid place. Updating to a more-current Scribd embed tag (which doesn't try to use Flash, and is https) fixed it.
