### ISSUE TITLE
Days with no posts hidden from daily view

### ISSUE THREAD

**Issue by jpaddison3** [LessWrong2/Lesswrong2#1130]
User suggestion
> I'd argue that days where there are no posts should just not show on the daily page, just makes it look more cluttered

**Comment by Discordius** [comment]
Nah, I think that's bad and makes it harder to orient.

**Comment by jimrandomh** [comment]
The Daily page used to have an issue where, due to time zone oddities, the first day shown is actually tomorrow, and has no posts. That's not so good, but, as part of the timezone rework, I put in a special case which excludes one empty day from the top. There also used to be jank where days would be incorrectly shown as empty during loading transitions, which was bad, but that's fixed now too.

Empty days in the *middle* are quite rare on lesswrong (and in the long run, will probably be nonexistent, unless you're looking through a filter). When they do exist, though, I agree with Oliver that it's easier to orient if they're shown.
