### ISSUE TITLE
The notifications icon should display the number of unread notifications

### ISSUE THREAD

**Issue by Discordius** [LessWrong2/Lesswrong2#129]

**Comment by Discordius** [comment]
Related to #228

**Comment by jimrandomh** [comment]
It also doesn't seem to change based on whether there are unread notifications or not. I just checked on LW and discovered that I had a ton of unread notifications that I didn't know about!

**Comment by jimrandomh** [comment]
Actually hmm, that's not quite what's going on. There are a bunch of subtle problems, but none as simple as the icon just not displaying number of unread notifications.

**Comment by Discordius** [comment]
Yeah, those are annoying. Unclear what to do about race conditions without
making everything much more complicated. Might have to bite the bullet and
make it dependent on the specific notifications (which requires more data
to be loaded on sync).

The notifications icon does have intentionally no number of notifications,
to not grab people's attention. It does change based on there being
notifications, but not too noticeably, since I don't want the icon to
distract from the content and become the centerpiece of LW, in the way it
is for FB.

**Comment by jimrandomh** [comment]
A simple fix: when you click on the icon it updates a field recording the time you clicked on the icon, but it updates it to the *current* time rather than to the *sync* time. Changing it to update to the sync time isn't perfect (notifications can still go unnoticed for awhile because it doesn't sync very often), but it at least prevents things from being marked as read when they aren't.

**Comment by jimrandomh** [comment]
I think the safe thing to do is to give it the same level of prominence it had on old-LW, which is considerably more prominent than it is now. The reason it's such a problem on Facebook is not because it's particularly prominent (it isn't), but because it dynamically adjusts what counts as a notification in order to act as an optimal intermittent reward button, and includes a lot of things that aren't legitimate reasons to be notified.
