### ISSUE TITLE
Comments don't fold and fold-comment button broken

### ISSUE THREAD

**Issue by ben-pace** [LessWrong2/Lesswrong2#1290]
I think the recent 'expand comments' feature may have broken the feature where comments with less than -5 karma are autoccollapsed.

See this one: https://www.lesswrong.com/posts/bRGbdG58cJ8RGjS5G/no-really-why-aren-t-rationalists-winning#6Lu936GBeDnrRQDve

The comment lets you click the + symbol to expand it, but it's already expanded

**Comment by jimrandomh** [comment]
@Raemon It looks like the `[+]`/`[-]` icon was repurposed to mean truncate/Read More instead of fold/unfold, but the change was only part-way finished. Post bodies now never fold (hence -5 karma not causing folding), and clicking the `[+]`/`[-]` button on a comment will expand a Read More. *But* clicking the `[+]`/`[-]` button on a comment will *also* hide that comment's replies. The overall effect is... very weird.
