### ISSUE TITLE
Disallow editing of old html posts.

### ISSUE THREAD

**Issue by Raemon** [LessWrong2/Lesswrong2#1460]
See this conversation with Wei Dai for why this is a problem:

https://app.intercom.io/a/apps/wtb8z7sj/inbox/inbox/all/conversations/19792920383

**Comment by Discordius** [comment]
I think the current behavior here is the correct one. You can edit them, but if you do, they show up in the original HTML in the editor. My guess is that he only ran into problems because he tried to edit it on GW. 

I don't want to block users out of editing their old posts, so allowing them to edit the HTML directly (though it will get sanitized when doing so) seems like the best choice.
