### ISSUE TITLE
Styling inconsistency on not found pages

### ISSUE THREAD

**Issue by FerociousTruth** [LessWrong2/Lesswrong2#178]
If I go to these two URLs that don't exist the text "Sorry, we couldn't find what you were looking for." appears at two very different sizes.  While this is relatively minor, it may point so some more fundamental issue about style sheet loading.

https://www.lesserwrong.com/posts/QKbzD7zrbCyQEWQya/draft-link/
![image](https://user-images.githubusercontent.com/19802624/31128952-325b830a-a821-11e7-8680-071be60e3134.png)

https://www.lesserwrong.com/sdfjgdfkjgndfkgdf
![image](https://user-images.githubusercontent.com/19802624/31128972-468eedbc-a821-11e7-95aa-57d4d4a1b3eb.png)

**Comment by Discordius** [comment]
I think those are actually just different components that happen to have the same text. Seems easy to fix though. 

In general we probably want to have better error page styling. Error pages are a pretty critical thing to get right, since users find them usually at the height of their frustration.

**Comment by jimrandomh** [comment]
This happens because two places (`PostsPage` and `UsersProfile`) write out the string, while `vulcan-router` uses `Components.Error404`. Making those two places also use the component makes the styling consistent. However, there's a bigger issue, which is that in all three cases the site is actually returning `200 OK`; it won't generate a true 404 no matter what.
