### ISSUE TITLE
Lost curation and PM emails if sent from lessestwrong

### ISSUE THREAD

**Issue by jimrandomh** [LessWrong2/Lesswrong2#1786]
When an admin clicks the Curate button, people who've signed up for email notifications of curated posts get emailed, and the emails are sent by whichever server they were using when they clicked the curate button. Unfortunately, many of the admins are using the test server (lessestwrong.com), while only the production server is able to send emails. So curation emails aren't getting reliably sent.

**Comment by roryokane** [comment]
I know nothing about the problem beyond what you described, but I thought it might be helpful to list some possible solutions:

- Disable the Curate button in all environments that are unable to send emails. The button should have a tooltip or nearby text that explains why it is disabled.
    - If it doesn’t exist already, a link, bookmarklet, or browser extension to view the same page on the production server could save time for the admin when they notice that the button is disabled.
- Connect the test server to the email-sending component of the production server, so that it is able to send emails. However, this risks sending emails with untested code.

Those are the only reasonable solutions I could think of. The first one sounds better to me.
