### ISSUE TITLE
The imported links from the original LW1.0 link posts appear to sometimes be broken

### ISSUE THREAD

**Issue by Discordius** [LessWrong2/Lesswrong2#22]

**Comment by WalkerCodeRanger** [comment]
I assume this issue is the same as what I am seeing.  For example, the link post from LW http://lesswrong.com/lw/o1r/how_feasible_is_the_rapid_development_of/ appears as https://www.lesserwrong.com/posts/Bqht6nhhPkJWcRAFd/how-feasible-is-the-rapid-development-of-artificial in LW 2.0 but that page doesn't actually have a link on it. Clicking the title does nothing and no other link can be found.

**Comment by jimrandomh** [comment]
Duplicate of #489 .
