### ISSUE TITLE
text persists in search bar

### ISSUE THREAD

**Issue by jecneps** [LessWrong2/Lesswrong2#242]
when I type in a search, and later go back to the search bar, my previous search text is still there. Seems like an unplanned annoying effect.

**Comment by Raemon** [comment]
Anyone tackling this may also want to handle:

https://github.com/Discordius/Lesswrong2/issues/242

**Comment by crybx** [comment]
Clicking the x on the search box hides the search results, and clicking the search icon again reshows the same text and results, unless you type something else for a new search. I like this behavior and am not a fan of changing it. It seems like a feature that I can easily get back to my search results without needing to spawn a bunch of tabs to check individual results.

**Comment by Raemon** [comment]
Hmm. Mileage may vary I guess.

Usually when I want to search I want to open things in separate tabs anyway (because I'm currently in the middle of something on the original page, that I don't want to lose). So the main impact of this situation is that whenever I go to search for a new thing, I have to first delete the previous thing I searched for, which was sort of annoying.

I'd prefer to handle the sort of thing you're describing here via a list of recent-searches or something. However, that's a bit more work, and I don't have a strong opinion about whether this fix gets made before a more fleshed out recent-search list gets implemented.

**Comment by Raemon** [comment]
(I am lowering the priority on this to "low", meanwhile)
