### ISSUE TITLE
Multiple problems

### ISSUE THREAD

**Issue by arromdee** [LessWrong2/Lesswrong2#280]
* Feature request: See all replies to your own comments or posts
* Feature request: Set defaults for sorting.  The user should not have to manually change the sorting each time.
* Feature request: A way to see all posts.  The current "see all posts" gives you a *preview* of the first few lines of each posts, it does not actually let you see the posts themselves.  Since it excludes Meta, it should also be worded so as to indicate that.  "All posts except Meta".
* Also, when I try that, I get some text from the post, then several inches of blank space before the edge of the page, which is even worse.
* Assuming that "blog posts" are just posts, Meta posts don't show up in the user's profile under "recent blog posts", which is inconsistent with the behavior of comments. (Also, I would suggest getting rid of the term "blog posts".)  If "blog posts" are distinct from posts, then there doesn't seem to be a way to see a user's posts at all.
* A less hidden way to see recent comments.
* Feature request: Option to display a post with narrower gutters.
* Feature request: A way to edit the raw text of a post, and a "formatting help" link.  Also, the parser is too aggressive; I had underscores in the middle of two words and it insisted on interpreting that as italics.
* Submitting a post does not immediately show the post, but it also provides no feedback that the post will be reviewed, or will be posted in the future, or anything else which lets the user distinguish this from silently dropping the post on the floor.
* IE at work (windows) will not work because LOGIN does nothing and no conversations icon appears at the lower right.  Firefox at home (Linux) has the same symptoms.  Firefox at work (Windows) produces formatting problems where many icons show up as text; for instance an arrow is "expand_more".  The Firefox on Linux is not blocking cookies or ads (and is a profile I specifically created to allow everything).  The IE at work is not blocking cookies or ads and the Firefox at work has some cookies blocked but *shouldn't* be blocking any from LW.  Chromium on Linux and Chrome on Windows works properly.

**Comment by Discordius** [comment]
Thanks for all the issues! It would be great if you could break these into separate issues. 

"Submitting a post does not immediately show the post"

Not sure what you mean by this. Submitting a post brings you to the page of the post.

**Comment by Discordius** [comment]
"Submitting a post does not immediately show the post"

Not sure what you mean by this. Submitting a post brings you to the page of the post.

**Comment by Discordius** [comment]
"IE at work (windows) will not work because LOGIN does nothing and no conversations icon appears at the lower right. Firefox at home (Linux) has the same symptoms. Firefox at work (Windows) produces formatting problems where many icons show up as text; for instance an arrow is "expand_more". The Firefox on Linux is not blocking cookies or ads (and is a profile I specifically created to allow everything). The IE at work is not blocking cookies or ads and the Firefox at work has some cookies blocked but shouldn't be blocking any from LW. Chromium on Linux and Chrome on Windows works properly."

This is probably a browser versioning issues, we currently only support the last three major browser versions. Browser versions for all of these would be super useful to verify this.

**Comment by Discordius** [comment]
"Feature request: Option to display a post with narrower gutters."

The whole thing is centered with fix-width, so the only thing that one could implement is a longer line-length, though it would definitely deteriorate readability very quickly. I don't think this is a good idea for 98% of users, so I don't think offering a line length with more than 100 characters per line makes sense in almost any circumstance. 

For the rare occasion where someone does really care, using a custom client-side stylesheet seems like the correct choice.

**Comment by Discordius** [comment]
"Feature request: A way to see all posts. The current "see all posts" gives you a preview of the first few lines of each posts, it does not actually let you see the posts themselves. Since it excludes Meta, it should also be worded so as to indicate that. "All posts except Meta"."

This seems potentially doable. Though I don't actually believe that this would be particularly useful. I.e. imagine a view on Reddit that shows you every post in full. By nature this wouldn't be very useful, because you are almost never in a situation where you want to fully read every post on Reddit. 

We have an RSS, which feels like the correct solution to this if someone wants more control over how to read all the posts.

**Comment by Discordius** [comment]
"Assuming that "blog posts" are just posts, Meta posts don't show up in the user's profile under "recent blog posts", which is inconsistent with the behavior of comments. (Also, I would suggest getting rid of the term "blog posts".) If "blog posts" are distinct from posts, then there doesn't seem to be a way to see a user's posts at all."

Meta posts shouldn't show up anywhere except Meta, though it might make sense to have a filter option on someone's profile that allows you to see their meta posts. The point of separating Meta from the rest is to make it so that your content there does not give you karma, and generally does not interfere with the normal side experience. 

Comments from meta also shouldn't be crossposted to the frontpage, but I haven't gotten around to implement that yet.

**Comment by Discordius** [comment]
"A less hidden way to see recent comments." 

It's on the frontpage, so I assume you mean a link to the recent comments section that is less hidden? I think that's reasonable and we should get around to it.

**Comment by Discordius** [comment]
"Feature request: A way to edit the raw text of a post, and a "formatting help" link. Also, the parser is too aggressive; I had underscores in the middle of two words and it insisted on interpreting that as italics."

Yeah, I need to improve the parser. Raw text sadly isn't possible, since we simply don't store posts as raw text, but as JSON objects, and it's really hard to control certain design stuff in markdown-like markup (for example alignment, which is not handled by markdown). 

For now I think the correct call for us is to support markdown input, but have most people use the inline-toolbar and normal keyboard shortcuts for styling. I would be happy about input on what rules might make the parser do reasonable things.

**Comment by Discordius** [comment]
"Also, when I try that, I get some text from the post, then several inches of blank space before the edge of the page, which is even worse."

It feels like a sentence before this is missing. What is "that" referring to?

**Comment by Discordius** [comment]
"Feature request: See all replies to your own comments or posts
Feature request: Set defaults for sorting. The user should not have to manually change the sorting each time."

These are both reasonable and should be implemented. I have some plans for this.

**Comment by arromdee** [comment]
> Not sure what you mean by this. Submitting a post brings you to the page of the post.

Okay, to rephrase: If I submit the post and then go back to the front page (of Meta in this case) the post I submitted is not there.  Yet when I submitted it I didn't get a message saying "your post is being held" or "posts can take several minutes to show up" or anything like that.  For all I know it contained a prohibited word and was dropped on the floor just like posts containing bad words at SSC.

>This is probably a browser versioning issues, we currently only support the last three major browser versions. Browser versions for all of these would be super useful to verify this.

At work (windows): Firefox is 56.0 32 bit.  IE is 11.0.9600.18665, Update Versions: 11.0.42.

I will edit this post to add in Linux version later.

Just in case, is there anything that I need in the way of cookies, non-blocked sites (work probably blocks some things), etc.?

**Comment by arromdee** [comment]
Rephrasing again: I said "all posts" but I agree that all posts would not be very useful.  "All comments", however, is far more useful, exists for real at lesswrong 1, and has the same problems at lesswrong 2.0 that "all posts" has--it doesn't actually show all of them, it just shows the first few lines.

**Comment by arromdee** [comment]
Linux version: Firefox 45.02 (I probably should update this one).

**Comment by Discordius** [comment]
Almost a year since this happened, but I think we implemented almost all the features from this issue that we would want in the long-run. There are some that we might still want to get to in the long run, but closing for now. Thanks again for putting so much effort into this at the time!
