### ISSUE TITLE
Posts scroll to top when reloaded

### ISSUE THREAD

**Issue by Ezra** [LessWrong2/Lesswrong2#295]
(Samsung Internet on Samsung Galaxy S8)

When an article is reloaded - either manually or by switching out of the browser and back - articles scroll back to top (or to anchor, if a footnote link was followed). It would be a much better reader experience if the position in the page was retained.

**Comment by Throne3d** [comment]
I've experienced this on Chrome, also (Chrome Beta, version 63.0.3239.52 – on Arch Linux desktop). It seems to intermittently save my location, but that could just be the browser doing that for me. In particular it looks like it loses it when I manually refresh the page, which can be inconvenient if I'm looking at comments, want to reload the page in case there's been an update, and then have to scroll back down again..

**Comment by Kinrany** [comment]
I'm experiencing this on Firefox 58.

Also mentioned in #263.

**Comment by jglamine** [comment]
Some friends and I have noticed this too - it's pretty annoying especially when reading long articles and comment chains.

**Comment by jglamine** [comment]
@Discordius @Raemon I've investigated this and am ready to implement a fix, so long as you're OK with my approach.

Because this is a single-page react application, we can't rely on the browser's default scroll restoration. Instead, we're using [react-router-scroll](https://github.com/taion/react-router-scroll) to remember scroll positions. It supports restoration of scroll position on refresh, but @Discordius disabled it in [this commit](https://github.com/jglamine/Lesswrong2/commit/28e7c9549db42764e19bb33906dd1935d8fccb98).

@Discordius do you remember why you disabled it? The commit message doesn't give me enough context.

If I re-enable scroll restoration for page refreshes, we run into a second issue. When you refresh a page it first jumps to the top, then after several seconds it jumps down to your saved scroll position. This happens because react-router-scroll disables the browser's default scroll restoration using the [custom scroll restoration API](http://majido.github.io/scroll-restoration-proposal/history-based-api.html).

So the initial server-rendered page doesn't remember the scroll position, but once react loads it restores the scroll position.

There's typically a several second delay between when the server-side rendered page loads and when react loads. During that time the user might start reading or scrolling, so just re-enabling scroll restoration for page refreshes would still result in a poor user experience.

I can think of a few solutions:

1. re-enable scroll restoration for page refreshes, and also re-enable the browser's default scroll restoration
    * This is not ideal because having both enabled can cause problems when pressing the "back" and "forward" buttons - first the default browser scroll restoration will happen, then the JavaScript based scroll restoration will happen, potentially causing a double scroll.
2. re-enable scroll restoration for refreshes, and add some inline-javascript to enable the browser's default scroll restoration on page load.
    * Once the main JavaScript bundle loads, the browser's default scroll restoration will be disabled again, so this only effects the first page load.
    * But inline javascript is kind of icky
3. Don't re-enable scroll restoration for page refreshes, but DO re-enable the browser's default scroll restoration
   * This has the same problem as 1
4. Same as 1, except only use JavaScript to update the scroll position if it's more than 50px away from the saved position.
5. Same as 3, except only use JavaScript to update the scroll position if it's more than 50px away from the saved position.

If you have any insight or comments, let me know. Within the next few days I'll try out some of these solutions and submit a pull request with whichever one I end up liking best.

Right now I'm leaning towards 1 for simplicity, but if it messes up scrolling too much I might go with 2.

**Comment by Raemon** [comment]
An option here is to pick an option, and Oli or I can deploy it to lessestwrong.com for a few days for the few of us to beta test, and then if it turns out to drive us crazy for alternate reasons we can then fine-tune it.

I don't have an obvious preference for any of the options – seems fine to start with the simplest one, see if it's annoying somehow and then add epicycles until it stops being annoying.

**Comment by Discordius** [comment]
I remember doing this because it caused weird double-scroll behavior when linking to comments. But not super sure.

**Comment by jpaddison3** [comment]
Reviewing recent diffs led me here. I'm still seeing this on mobile, and it remains one of my bigger complaints as a user. Do y'all still think it's solved? I can try to work on getting a repro if so.

**Comment by jglamine** [comment]
If I can reproduce the issue I can try to help. Which browser version and
operating system are you using?

**Comment by jpaddison3** [comment]
Chrome 68.0.3440.91, Android 9.0.0, Pixel 2 Build/PPR1.180610.009.
Should just be latest everything on android.

**Comment by jpaddison3** [comment]
If I refresh a page it's fine. Was that not true before? Maybe this is a
different issue. This occurs when coming back after visiting other tabs,
apps, etc. Will try to get minimal repro. ... Hmm, I'm getting it to reload
itself after opening other tabs and apps, but it's still getting to the
same place. ... 🧐
That's annoying. Will let y'all know if I see it again.

**Comment by jglamine** [comment]
What you're seeing is a separate issue - the page is set to automatically
reload itself when a new version of the site is deployed. I agree that this
is annoying and should be disabled.

Last time I brought this up they wanted to keep the auto reloading for fear
that the site would appear broken on old clients.

I'll bring this up at today.

**Comment by jglamine** [comment]
It's also possible that it remembers your scroll position fine during
auto-refresh. I'm not sure.

**Comment by jimrandomh** [comment]
Possible solutions are:

 * Find an API for mucking with scroll-restore (might not exist)
 * Server-side render the comments
 * Insert a tall placeholder in the initial render to ensure the page is at least as tall as it was before the refresh

**Comment by jglamine** [comment]
@jimrandomh Great job figuring out that the issue only happens when you're scrolled past the comments. Let's track this as a new issue so that we can have a concise summary in the issue description. I've opened #884 to track this

@jpaddison3  Thanks for reporting!
