### ISSUE TITLE
Page with different numbers of comments in TOC than really are

### ISSUE THREAD

**Issue by edoarad** [LessWrong2/Lesswrong2#3134]
this is after refreshing the page 
https://www.lesswrong.com/posts/RKz7pc6snBttndxXz/literature-review-for-academic-outsiders-what-how-and-why-1
![image](https://user-images.githubusercontent.com/24963373/81777172-f5829f00-94f8-11ea-8437-db1d0d9e5087.png)

**Comment by jimrandomh** [comment]
The bug is in `packages/lesswrong/server/tableOfContents.ts:220` which is doing a count-query on comments using a manually specified selector, rather than getting the selector from the default view. As a result it's missing some of the criteria which cause comments to not be shown (in this case, the comment was deleted by its author.)
