### ISSUE TITLE
pingbacks feature does not count links to sections within post

### ISSUE THREAD

**Issue by zackmdavis** [LessWrong2/Lesswrong2#3841]
["Unnatural Categories Are Optimized for Deception"](https://www.lesswrong.com/posts/onwgTH6n8wxRSo2BJ/unnatural-categories-are-optimized-for-deception) contains links (using `#` anchors) to sections within ["Generalized Efficient Markets in Political Power"](https://www.lesswrong.com/posts/YMtZRGLbvdD4BGaqN/generalized-efficient-markets-in-political-power#Governance_as_Schelling_Point) and ["Credibility of the CDC on SARS-CoV-2"](https://www.lesswrong.com/posts/h4vWsBBjASgiQ2pn6/credibility-of-the-cdc-on-sars-cov-2#Discouraged_Use_of_Masks), neither of which registered a pingback. I find this behavior counterintuitive.

**Comment by Discordius** [comment]
Yeah, that does seem wrong and counterintuitive.

**Comment by jimrandomh** [comment]
Fixed in upcoming release (on the meteor-to-express conversion branch). It was assuming that the anchor was a comment ID, and since pingbacks on comments aren't supported yet, ignoring it. Changed it so that links to comments just pingback on the post, without special case handling on comments. After deploy we'll want to rerun the `generatePingbacks` migration to apply the change retroactively.
