### ISSUE TITLE
Legacy rss feeds are broken

### ISSUE THREAD

**Issue by jglamine** [LessWrong2/Lesswrong2#519]
I am subscribed to two RSS feads from lesswrong version 1. They are:

http://lesswrong.com/promoted/.rss
http://lesswrong.com/r/discussion/top/.rss

I don't know how popular these feeds are, but it would be nice if they still worked.

**Comment by Discordius** [comment]
Good point. We could easily fix those.

**Comment by jimrandomh** [comment]
These are now 301 redirects (instead of endpoints that hang/crash). Feedly doesn't seem to have noticed though - that might either be because Feedly doesn't consider a redirect to be a real feed, or because it has a slow update interval. If new posts don't appear in 48h, I'll assume it's the former, and we can make the legacy endpoints be regular feeds rather than redirects.

**Comment by Discordius** [comment]
Thanks, there is some chance some other bugs were caused by this.

**Comment by jglamine** [comment]
Nice work!

**Comment by jimrandomh** [comment]
Feedly did, in fact, pick up on the feeds having come back to life. So everyone who was subscribed to the old feeds and had their feed stop working, is now subscribed to Curated.
