### ISSUE TITLE
Recent/Top comments are not formatted with Markdown

### ISSUE THREAD

**Issue by jessica-taylor** [LessWrong2/Lesswrong2#523]
Top comments appear in plaintext, e.g. links look like \[this\]\(...\).

![2018-04-11-112244_947x658_scrot](https://user-images.githubusercontent.com/566984/38635773-41bf472e-3d7b-11e8-80bd-6f1b0fedb9aa.png)

**Comment by Raemon** [comment]
Yup – we only recently set up the tools we need to properly truncate comments when they're properly formatted. (ie. it's actually a bit tricky to slice something down to 300 characters while preserving it's formatting).

The old implementation for comments was "they started out as a non-formatted truncated version, and then become properly-formatted-and-expanded when you click on them."

We'll be fixing this sometime soon(ish) now that we have better tech for converting things to markdown and back, although probably not for a few more weeks at least due to competing priorities.
