### ISSUE TITLE
RSS includes spam posts

### ISSUE THREAD

**Issue by vkrakovna** [LessWrong2/Lesswrong2#554]
The RSS feed www.lesswrong.com/feed.xml (viewed in Feedly) includes spam posts (e.g. "Fidelity Plumbers West Seattle").

**Comment by Raemon** [comment]
Hmm. I'm not actually that familiar with RSS (either in general or LessWrong's implementation), but first thoughts include:

Is RSS supposed to "retract" things that get heavily downvoted or deleted? Is the issue that the post hasn't been deleted or heavily downvoted, or that, having been so, it didn't get removed from the RSS feed?

(If the former, the main issue is about improving our response time to deleting spam, if the latter, the issue is more about improving the RSS feed)

**Comment by vkrakovna** [comment]
I don't see the spam posts on LessWrong itself - I assume they have been deleted, but that didn't propagate to the RSS feed.

**Comment by crybx** [comment]
RSS readers (e.g. Feedly, Inoreader, etc.) cache the data they get from various feed urls to enable long term history for their users. Without caching, RSS readers would only be able to display the X most recent posts, since feeds usually don't send a website's entire content. This means that once the spam is in Feedly, content creators from the original website can't get it out. There's no retraction. Once the spam is deleted on the website, it no longer appears in the feed at its source (e.g. www.lesswrong.com/feed.xml), but there are so many RSS readers apps that may have all sorts of different caching behavior you couldn't hope to control.

So stopping the spam in the feeds will probably take stopping the spam from getting posted in the first place.

**Comment by kenny-evitt** [comment]
This should probably be closed. There doesn't seem to be anything actionable, beyond '*prevent* spam'.

**Comment by jimrandomh** [comment]
Deleting things doesn't work well in Feedly, but this is certainly solveable. I think the best solution is to put a combination karma minimum plus short time delay on all the feeds people are likely to be subscribed to, so that if the first votes a post get are downvotes and it never gets to a positive score, then it doesn't appear in feeds.
