### ISSUE TITLE
If webfonts are disabled, icons suck

### ISSUE THREAD

**Issue by Raemon** [LessWrong2/Lesswrong2#616]
From intercom:

This website still looks awful for those of us with webfonts disabled. Please fix this.

![image](https://user-images.githubusercontent.com/3246710/41001087-c8e94190-68c4-11e8-80a2-29610d2b5274.png)

**Comment by jimrandomh** [comment]
This happens because icons are coming from material-ui's "icon font". Which browser has a disable-webfonts setting, and how widely used is it? Some Googling suggests Chrome can do it with a command-line flag, but not from the settings pages; this might be in the same reference class as users having disabled Javascript (ie, not worth the architecture change required to fix).
