### ISSUE TITLE
Sequence Post – So Called Heisenberg Uncertainty Principle images

### ISSUE THREAD

**Issue by Raemon** [LessWrong2/Lesswrong2#631]
From intercom:

On the https://www.lesswrong.com/posts/eWuuznxeebcjWpdnH/the-so-called-heisenberg-uncertainty-principle article I noticed that some of the images seems to have switched sides - So there text refers to an image on the left while it's actually on the right

**Comment by jimrandomh** [comment]
It looks like all the images lost their "style" tags in the import, and the style tags included `float:right` and `float:left` for some of the images in this case. It's easy enough to edit this particular post to fix it; ideal would be to bulk-search all the imported posts for similar problems while we're at it.

**Comment by jimrandomh** [comment]
Soft dependency (could work around by manually editing HTML, but I'd rather not): https://github.com/LessWrong2/Lesswrong2/issues/706

**Comment by jimrandomh** [comment]
I did some general formatting cleanup, but it looks like the confusingness of the image positions goes all the way back to its original form on Overcoming Bias, across two imports - https://web.archive.org/web/20081005094354/http://www.overcomingbias.com/2008/04/heisenberg.html .

Converted some underlines that were supposed to represent markdown italics, to italics. Images that were supposed to be floats and had single lines of text awkwardly beside them, are now centered blocks, since our current editor doesn't actually support floats. (#733)
