### ISSUE TITLE
Karma not visible from front page

### ISSUE THREAD

**Issue by jimrandomh** [LessWrong2/Lesswrong2#729]
On old-LW, as a logged in user your karma was visible on the front page. This meant that if you've posted recently and are getting upvotes, you _know_ you're getting upvotes, which makes them more effective as a reward signal. Currently, you can only see your karma by going to your profile page. This weakens the microhedonics that keep people coming to the site.

**Comment by jimrandomh** [comment]
Just displaying your karma all the time might not be what we want to do; there's a variety of options here. For example, rather than show a total karma, we might show reminders of what your recent posts/comments were and how much their score has gone up since you last checked. We might show the names of particular high-status people who've upvoted you (caveat anonymity concerns). Whatever we do, though, it's important that the microhedonics are *at least* as good as the old site. And at least as good as the competition--Reddit and HN both display your total karma all the time, Facebook notifies you of Likes mostly individually but with a clever batching scheme if there are too many, Tumblr and Twitter notify you when people Follow.

**Comment by Raemon** [comment]
This sort of issue I'd like to register a slight preference for conducting
in the meta forum (note: I don't know whether Oli endorses this or not).
I'd like us to err more than we currently do on the side of having
philosophical hash-outs in public spaces so people can follow them and
weigh in (assuming we trust ourselves to stick with our actual best guess
rather than going with the people who are loudest)

**Comment by jimrandomh** [comment]
This has been an open PR (https://github.com/LessWrong2/Lesswrong2/pull/858) for awhile now; it's blocked on making a policy decision.

**Comment by jimrandomh** [comment]
Karma-change notifier has been live for awhile now.
