### ISSUE TITLE
500 internal server error message when logging in with nonexisting username

### ISSUE THREAD

**Issue by Discordius** [LessWrong2/Lesswrong2#820]
Sam: If you try to log in with a non-existent username (e.g. I tried `samdeere` instead of `sam`) then you get a `500 Internal Server Error` at the bottom of the login dropdown. This was confusing and it took me a while to realise my mistake, would suggest a specific error message here.

**Comment by jimrandomh** [comment]
Testing on the production site: If I try to log in as a nonexistent but valid username, I get a "User not found" message. If I try to log in as a nonexistent email address, I get "Wrong passord" instead. I haven't succeeded at getting a `500 Internal Server Error` out of the login form via any method; whatever the problem is, it's not as simple as just a non-existent username. Is there something in the server logs, perhaps?

**Comment by jimrandomh** [comment]
This predates a Vulcan version upgrade which included mostly rewriting the `vulcan-accounts` package, and I (still) can't replicate it. So I think this is probably not an issue.
