### ISSUE TITLE
Animation for "Hide low karma" checkbox on Daily page is misaligned

### ISSUE THREAD

**Issue by jimrandomh** [LessWrong2/Lesswrong2#843]
When you click the "Hide low karma" checkbox on `/daily`, there's an animation that's supposed to be a glowy circle around the checkbox. Instead, it's a glowy circle 30px to the left of the checkbox.

This predates the styles refactor.

**Comment by Discordius** [comment]
Finally. After this we should properly announce the LW 2.0 codebase as stable, and bug free. 

Though we might want to hold off on making this public knowledge too soon. This being fixed might just cause the greaterwrong crew to stop working, since they might think all of their work is done and there is no way to compete with LW 2.0.
